---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_solo

platforms:
  - name: debian-7
    driver_config:
      image: debian:7.8
  - name: debian-7-chef-11.x
    driver_config:
      image: debian:7.8
      require_chef_omnibus: 11.18.12
  - name: ubuntu-12.04
    driver_config:
      image: ubuntu:12.04
  - name: ubuntu-12.04-chef-11.x
    driver_config:
      image: ubuntu:12.04
      require_chef_omnibus: 11.18.12
  - name: ubuntu-14.04
    driver_config:
      image: ubuntu:14.04
    attributes:
      td_agent:
        version: 2
  - name: ubuntu-14.04-chef-11.x
    driver_config:
      image: ubuntu:14.04
      require_chef_omnibus: 11.18.12
    attributes:
      td_agent:
        version: 2
  - name: centos-6
    driver_config:
      image: centos:centos6
  - name: centos-6-chef-11.x
    driver_config:
      image: centos:centos6
      require_chef_omnibus: 11.18.12

suites:
  - name: default
    run_list:
      - recipe[td-agent::default]
      - recipe[smoke::default]
    attributes:
      td_agent:
        includes: true
  - name: td-agent-1.x
    run_list:
      - recipe[td-agent::default]
      - recipe[smoke::default]
    attributes:
      td_agent:
        version: 1
    excludes:
      - debian-7
      - debian-7-chef-11.x
      - ubuntu-14.04
      - ubuntu-14.04-chef-11.x
