---
################################################################################
# Any local customizations should be placed inside the .kitchen.local.yml, which
# will not be checked in or overwritten. You may also use ~/.kitchen/config.yml
# or environment variables like VAGRANT_DEFAULT_PROVIDER. Anything in those will
# take precedence over anything set in `.kitchen.yml`.
################################################################################
driver:
  name: vagrant # provide a default test-kitchen driver, vagrant

provisioner:
  name: chef_zero
  nodes_path: 'test/fixtures/nodes'
  data_bags_path: 'test/fixtures/data_bags'
  environments_path: 'test/fixtures/environments'
  client_rb:
    environment: _default
  attributes:
    java:
      jdk_version: '7'

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.6
    run_list:
    - recipe[yum]
    - recipe[elasticsearch_test::fix_nss] # see recipe header

suites:
  - name: default # the normal use-case
    require_chef_omnibus: 12.4.1
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::default_with_plugins]

  - name: elasticsearch_test # the override-everything use case
    driver_config:
      require_chef_omnibus: 12.4.1
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::default]

  - name: chef-12.3.0
    driver_config:
      require_chef_omnibus: 12.3.0
    includes:
      - ubuntu-14.04
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::default_with_plugins]

  - name: chef-12.2.1
    driver_config:
      require_chef_omnibus: 12.2.1
    includes:
      - ubuntu-14.04
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::default_with_plugins]

  - name: chef-12.1.2
    driver_config:
      require_chef_omnibus: 12.1.2
    includes:
      - ubuntu-14.04
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::default_with_plugins]

  - name: chef-11.18.12
    driver_config:
      require_chef_omnibus: 11.18.12
    includes:
      - ubuntu-14.04
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::default_with_plugins]
